---
- name: Create Nextcloud directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nextcloud_data_directory }}/data"
    - "{{ nextcloud_data_directory }}/mysql"

- name: Nextcloud Mysql Docker Container
  docker_container:
    name: nextcloud-mysql
    image: mariadb
    pull: true
    networks:
      - name: "bockynet"
    purge_networks: yes
    volumes:
      - "{{ nextcloud_data_directory }}/mysql:/var/lib/mysql:rw"
    env:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "bcloud"
      MYSQL_PASSWORD: "{{ nextcloud_password }}"
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_root_password }}"
    restart_policy: unless-stopped
    memory: 1g

- name: Nextcloud Docker Container
  docker_container:
    name: nextcloud
    image: nextcloud
    pull: true
    networks:
      - name: "bockynet"
    purge_networks: yes
    links:
        - nextcloud-mysql:mysql
    volumes:
      - "{{ nextcloud_data_directory }}/nextcloud:/var/www/html:rw"
    ports:
      - "{{ nextcloud_port }}:80"
    env:
      MYSQL_HOST: "nextcloud-mysql"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "{{ nextcloud_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "bcloud.{{ ansible_nas_domain }}"
    restart_policy: unless-stopped
    memory: 1g
    labels:
      traefik.enable: "{{ nextcloud_available_externally }}"
      traefik.http.routers.nextcloud.tls: "true"
      traefik.http.routers.nextcloud.tls.certresolver: "bocky"
      traefik.http.routers.nextcloud.service: "nextcloud"
      traefik.http.routers.nextcloud.rule: "Host(`bcloud.bocky.nl`)"