[global]
  checkNewVersion = true
  sendAnonymousUsage = false

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"

  [entryPoints.websecure]
    address = ":{{ traefik_port_https }}"

      [entryPoints.websecure.http.tls]
        certResolver = "letsencrypt"

  [entryPoints.traefik]
    address = ":{{ traefik_port_ui }}"

[providers]
  providersThrottleDuration = "2s"

  [providers.file]
  directory = "/etc/traefik/conf"
  
  [providers.docker]
    exposedbydefault = false
    defaultRule = "Host(`{% raw -%}{{ normalize .Name }}{% endraw -%}.{{ ansible_nas_domain }}`)"

[api]
  insecure = true
  dashboard = true

[log]
  level = "{{ traefik_log_level }}"

[ping]
  terminatingStatusCode = 0

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "{{ ansible_nas_email }}"
      storage = "/letsencrypt/acme.json"
      caserver = "{{ traefik_acme_server }}"

      [certificatesResolvers.letsencrypt.acme.dnsChallenge]
        provider = "{{ traefik_dns_provider }}"
        resolvers = ["8.8.8.8:53", "8.8.8.8:53"]

[pilot]
    token = ""