---
- name: Create Plex Directories
  file:
    path: "{{ item }}"
    state: directory
    # mode: 0755
  with_items:
    - "{{ plex_config_directory }}"
    - "{{ plex_logs }}"

- name: plex Docker Container
  docker_container:
    name: plex
    image: linuxserver/plex
    pull: true
    volumes:
      - "{{ plex_config_directory }}:/config:rw"
      - "{{ plex_logs }}:/opt/plex/Library/Application Support/Plex Media Server/Logs:rw"
      - "{{ plex_movies_directory }}:/movies:{{ plex_movies_permissions }}"
      - "{{ plex_tv_directory }}:/tv:{{ plex_tv_permissions }}"
      - "{{ plex_photos_directory }}:/photos:{{ plex_photos_permissions }}"
      - "{{ plex_podcasts_directory }}:/podcasts:{{ plex_podcasts_permissions }}"
      - "{{ plex_music_directory }}:/music:{{ plex_music_permissions }}"
    networks:
      - name: "{{ docker_networkname }}"
    purge_networks: yes
    devices: "{{ plex_devices | default(omit) }}"
    env:
      NVIDIA_VISIBLE_DEVICES: "all"
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ plex_user_id }}"
      PGID: "{{ plex_group_id }}"
      VERSION: "{{ plex_version }}"
    restart_policy: unless-stopped
    #devices:
    #  - "/dev/dri:/dev/dri"
    memory: 2g
    labels:
      traefik.enable: "{{ plex_available_externally }}"
      #traefik.http.routers.plex.rule: "Host(`{{ plex_hostname }}.{{ ansible_nas_domain }}`)"
      #traefik.http.routers.plex.service: "plex"
      traefik.http.services.plex.loadbalancer.server.port: "32400"
      traefik.http.routers.plex.middlewares: "no-auth-chain@file" 
      traefik.http.routers.plex.rule: "Host(`px.bocky.nl`)"

